/** @format */

import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { NetworkProvider } from "./context/NetworkContext";
import { WalletProvider } from "./context/WalletContext";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Cheba",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={manrope.className}>
				<NetworkProvider>
					<WalletProvider>{children}</WalletProvider>
				</NetworkProvider>
			</body>
		</html>
	);
}
